// client/src/app/components/molecules/SideBar/SideBar.jsx
import React from 'react';
import PropTypes from 'prop-types';
import SideBarTab from './SideBarTab';

const SideBar = props => {
  const tabsData = [
    {'href': 'homeSubmenu', 'tabImage': 'fa-home', 'tabText': 'Home', 'activeClass': true, 'subList': false},
    {'href': 'about', 'tabImage': 'fa-briefcase', 'tabText': 'About', 'activeClass': false, 'subList': false},
    {'href': 'pageSubmenu', 'tabImage': 'fa-copy', 'tabText': 'Tasks', 'activeClass': false, 'subList': true},
    {'href': 'favorites', 'tabImage': 'fa-image', 'tabText': 'Favorites', 'activeClass': false, 'subList': false},
    {'href': 'question', 'tabImage': 'fa-question', 'tabText': 'FAQ', 'activeClass': false, 'subList': false},
    {'href': 'contact', 'tabImage': 'fa-paper-plane', 'tabText': 'Contact', 'activeClass': false, 'subList': false},
  ]
  const tabItems = tabsData && tabsData.map((tab) => {
    return <SideBarTab tab={tab} />
  })
  return (
    <div className="c-SideBar">
      <nav id="sidebar" class="active">
        <div class="sidebar-header">
          <button type="button" id="sidebarCollapse" class="btn btn-info">
            <i class="fas fa-align-justify"></i>
          </button>
          <h3 class="logotext">Microbot</h3>
        </div>
        <ul class="list-unstyled components">
          {tabItems}
        </ul>
      </nav>
    </div>
  )
};


SideBar.propTypes = {
  tabsData: PropTypes.array
};

export default SideBar;

// src/app/components/molecules/side-bar/side-bar.component.ts
import { Component, OnInit, Output } from '@angular/core';

@Component({
  selector: 'app-side-bar',
  templateUrl: './side-bar.component.html',
  styleUrls: ['./side-bar.component.scss']
})
export class SideBarComponent implements OnInit {
  
  @Output() tabsData = [
    {'href': 'homeSubmenu', 'tabImage': 'fa-home', 'tabText': 'Home', 'activeClass': true, 'subList': false},
    {'href': 'about', 'tabImage': 'fa-briefcase', 'tabText': 'About', 'activeClass': false, 'subList': false},
    {'href': 'pageSubmenu', 'tabImage': 'fa-copy', 'tabText': 'Tasks', 'activeClass': false, 'subList': true},
    {'href': 'favorites', 'tabImage': 'fa-image', 'tabText': 'Favorites', 'activeClass': false, 'subList': false},
    {'href': 'question', 'tabImage': 'fa-question', 'tabText': 'FAQ', 'activeClass': false, 'subList': false},
    {'href': 'contact', 'tabImage': 'fa-paper-plane', 'tabText': 'Contact', 'activeClass': false, 'subList': false},
  ]

  constructor() { }

  ngOnInit() {
  }

}

<nav id="sidebar" class="active">
  <div class="sidebar-header">
    <button type="button" id="sidebarCollapse" class="btn btn-info">
      <i class="fas fa-align-justify"></i>
    </button>
    <h3 class="logotext">Microbot</h3>
    <!-- <strong>MB</strong> -->
  </div>

  <ul class="list-unstyled components">
    <li *ngFor="let tab of tabsData"
        [ngClass]="{active: tab.activeClass}">
      <a [routerLink]="tab.href">
        <i [ngClass]="['fas', tab.tabImage]"></i>
        <span class="hideable hide">{{tab.tabText}}</span>
      </a>
      <ul 
        class="collapse list-unstyled" 
        id="pageSubmenu"
        *ngIf="tab.subList">
        <li>
          <a href="#">Repo</a>
        </li>
        <li>
          <a href="#">Issues</a>
        </li>
        <li>
          <a href="#">Admin</a>
        </li>
      </ul>
    </li>
    <!-- <app-side-bar-tab
      *ngFor="let tab of tabsData"
      [tab]="tab">
    </app-side-bar-tab> -->
    <!-- <li class="active">
      <a href="#homeSubmenu">
        <i class="fas fa-home"></i>
        <span class="hideable hide">Home</span>
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fas fa-briefcase"></i>
        <span class="hideable hide">About</span>
      </a>
    </li>
    <li>
      <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <i class="fas fa-copy"></i>
        <span class="hideable hide">Tasks</span>
      </a>
      <ul class="collapse list-unstyled" id="pageSubmenu">
        <li>
          <a href="#">Repo</a>
        </li>
        <li>
          <a href="#">Issues</a>
        </li>
        <li>
          <a href="#">Admin</a>
        </li>
      </ul>
    </li>
    <li>
      <a href="#">
        <i class="fas fa-image"></i>
        <span class="hideable hide">Favorites</span>
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fas fa-question"></i>
        <span class="hideable hide">FAQ</span>
      </a>
    </li>
    <li>
      <a href="#">
        <i class="fas fa-paper-plane"></i>
        <span class="hideable hide">Contact</span>
      </a>
    </li> -->
  </ul>
</nav>
